canonifyURLs: true
baseURL: "https://docs.rhize.com"
languageCode: en-us
title: Rhize documentation

module:
  imports:
  - path: github.com/imfing/hextra


menu:
  main:
    - name: Docs
      weight: 1
      url: /get-started/introduction
    - name: Learn ISA-95
      weight: 5
      url: /isa-95
    - name: Search
      weight: 10
      params:
        type: search
    - name: Youtube
      weight: 25
      url: "https://www.youtube.com/@rhizemanufacturingdatahub"
      params:
        icon: youtube
    - name: Discord
      weight: 30
      url: "https://discord.gg/ZRpUBXmrkV"
      params:
        icon: discord
    - name: LinkedIn
      weight: 40
      url: "https://www.linkedin.com/company/rhizemdh/"
      params:
        icon: linkedin
    - name: Talk to us
      url: "https://rhize.com/contact-us/"
      weight: 50



ignoreErrors:

markup:
  # allow raw html
  goldmark:
    renderer:
      unsafe: true
    renderHooks:
      link:
        enableDefault: true
  # enable hextra syntax highlight
  highlight:
    noClasses: false
enableEmoji: true

security:
  enableInlineShortcodes: true

params:
  site: rhize-docs
  editURL:
    base: "https://github.com/libremfg/rhize-docs/edit/main/content"
    enable: true
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: images/logo.svg
      dark: images/logo-dark.svg
      width: 100
      link: /
  footer:
    displayCopyright: false
    displayPoweredBy: false
    displayLogo: true

outputs:
  home:
    - HTML

permalinks:
  page:
    docs: /:slug/
  section:
    docs: /
