canonifyURLs: true
baseURL: "https://docs.rhize.com"
languageCode: en-us
title: Rhize documentation

module:
  imports:
  - path: github.com/imfing/hextra


menu:
  main:
    - name: Docs
      pageRef: /docs
      weight: 1
    - name: ISA-95
      weight: 2
    - name: Search
      weight: 4
      params:
        type: search
    - name: GitHub
      weight: 5
      url: "https://github.com/libremfg/rhize-docs"
      params:
        icon: github
    - name: Discord
      weight: 6
      url: "https://twitter.com/"
      params:
        icon: discord



ignoreErrors:

markup:
  # allow raw html
  goldmark:
    renderer:
      unsafe: true

  # enable hextra syntax highlight
  highlight:
    noClasses: false
enableEmoji: true

security:
  enableInlineShortcodes: true

params:
  site: rhize-docs
  editURL:
    base: "https://github.com/libremfg/rhize-docs/edit/main/content"
    enable: true
  navbar:
    displayTitle: true
    displayLogo: true
  footer:
    displayCopyright: false
    displayPoweredBy: false
    displayLogo: true
    logo:
      path: /images/logo.svg
      dark: images/logo-dark.svg
      width: 100
      link: /

outputs:
  home:
    - HTML
