canonifyURLs = true
languageCode = "en-us"
theme = "hugo-docs"
sectionPagesMenu = 'main'
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[markup.goldmark.renderer]
unsafe = true

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_','VERSION','CURRENT_VERSION','CANONICAL_PATH','CURRENT_BRANCH','DGRAPH_ENDPOINT']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "vs"
tabWidth = 4

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

# set by build script: title, baseurl
title = "RHIZE Baas Documentation"

[params]
discourse = "https://discuss.librebaas.io/"
site = "librebaas-docs"


