canonifyURLs: true
baseURL: "https://docs.rhize.com"
languageCode: en-us
theme: hugo-docs
sectionPagesMenu: main

ignoreErrors:
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: vs
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
    title: Rhize Documentation
security:
  enableInlineShortcodes: true
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
      - VERSION
      - CURRENT_VERSION
      - CANONICAL_PATH
      - CURRENT_BRANCH
      - DGRAPH_ENDPOINT
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
params:
  site: librebaas-docs

outputs:
  home:
    - HTML
